// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEiuqYX7bqiozxMk2yCJgrRr7UPeXUWaQ',
    appId: '1:962377215812:web:e82e52f17dee471043f111',
    messagingSenderId: '962377215812',
    projectId: 'flutterfb-89b4c',
    authDomain: 'flutterfb-89b4c.firebaseapp.com',
    storageBucket: 'flutterfb-89b4c.appspot.com',
    measurementId: 'G-S3K0B0LPG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADUPmVibth66S2bZI5pNqbecF7lTPNlok',
    appId: '1:962377215812:android:f0020ffc4ad21d5343f111',
    messagingSenderId: '962377215812',
    projectId: 'flutterfb-89b4c',
    storageBucket: 'flutterfb-89b4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR_uWr7kbbofUDzAERyPzWNaZ3DsIE-40',
    appId: '1:962377215812:ios:7ac8214daec5f5c143f111',
    messagingSenderId: '962377215812',
    projectId: 'flutterfb-89b4c',
    storageBucket: 'flutterfb-89b4c.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR_uWr7kbbofUDzAERyPzWNaZ3DsIE-40',
    appId: '1:962377215812:ios:0dcd241a9fe603db43f111',
    messagingSenderId: '962377215812',
    projectId: 'flutterfb-89b4c',
    storageBucket: 'flutterfb-89b4c.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
